package com.manastudent.db.domain;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_resource.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_resource.resource
     *
     * @mbg.generated
     */
    private String resource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_resource.id
     *
     * @return the value of u_resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_resource.id
     *
     * @param id the value for u_resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_resource.name
     *
     * @return the value of u_resource.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_resource.name
     *
     * @param name the value for u_resource.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_resource.resource
     *
     * @return the value of u_resource.resource
     *
     * @mbg.generated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_resource.resource
     *
     * @param resource the value for u_resource.resource
     *
     * @mbg.generated
     */
    public void setResource(String resource) {
        this.resource = resource;
    }
}