package com.manastudent.db.domain;

import java.time.LocalDateTime;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.validator
     *
     * @mbg.generated
     */
    private String validator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.createDate
     *
     * @mbg.generated
     */
    private LocalDateTime createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.id
     *
     * @return the value of u_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.id
     *
     * @param id the value for u_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.name
     *
     * @return the value of u_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.name
     *
     * @param name the value for u_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.validator
     *
     * @return the value of u_user.validator
     *
     * @mbg.generated
     */
    public String getValidator() {
        return validator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.validator
     *
     * @param validator the value for u_user.validator
     *
     * @mbg.generated
     */
    public void setValidator(String validator) {
        this.validator = validator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.createDate
     *
     * @return the value of u_user.createDate
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.createDate
     *
     * @param createdate the value for u_user.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(LocalDateTime createdate) {
        this.createdate = createdate;
    }
}